name: Terraform Destroy
on:
  workflow_dispatch:
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -destroy -out=tfplan
      env:
        TF_VAR_some_variable: ${{ secrets.SOME_VARIABLE }}
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_some_variable: ${{ secrets.SOME_VARIABLE }} # Add any required variables